### PR TITLE
Fix the precision/recall bug (fixes #12)

### LINKED ISSUE #12: A possible mistake in benchmark.py
In line 56~58,
```python
for goldEx in goldExtractions:   
    unmatchedCount += len(goldExtractions)
    correctTotal += len(goldExtractions)
```
Maybe the for loop is not needed since by doing the for loop you count  `len(goldExtractions)* len(goldExtractions)` times for `unmatchedCount` and `correctTotal` but only `len(goldExtractions)` times are enough for both.

### PR DESCRIPTION
**Pull request by AjayP13**
Fixes #12 in an independent pull request.

### CODE REVIEW

File: eval.sh [hunk 1]
```diff
@@ -2,7 +2,6 @@
 mkdir -p ./eval/
 python benchmark.py --gold=./oie_corpus/all.oie --out=eval/Stanford.dat --stanford=./systems_output/stanford_output.txt
 python benchmark.py --gold=./oie_corpus/all.oie --out=eval/OLLIE.dat --ollie=./systems_output/ollie_output.txt
-python benchmark.py --gold=./oie_corpus/all.oie --out=eval/ReVerb.dat --reverb=./systems_output/reverb_output.txt
```
Comment (AjayP13) [inline eval.sh:5]: ReVerb breaks when this bug is fixed. It seems like the `reverb_output.txt` file is actually broken. The sentence IDs don't correspond right to the sentence IDs in the ReVerb corpus. Temporarily removing this from `eval.sh` until it can be fixed. This shouldn't be a problem since ReVerb is predecessor to some of the later work like OpenIE-4?

Comment (gabrielStanovsky) [reply eval.sh:5]: Oh, let me take a look at this. 
Sounds good to defer this for now, I can open an issue if something's broken.

**Comment by gabrielStanovsky** [comment]
Looks good to me. 
Thanks!
